Fix: Google sign-in flowType error
The error `src/contexts/auth/useSignIn.ts(84,11): error TS2353: Object literal may only specify known properties, and 'flowType' does not exist in type '{ redirectTo?: string; scopes?: string; queryParams?: { [key: string]: string; }; skipBrowserRedirect?: boolean; }'.` indicates an invalid property in the `signInWithOAuth` options. This commit removes the `flowType` property from the `signInWithOAuth` options in `src/contexts/auth/useSignIn.ts` as it is not a valid option. The `flowType` is already set in the supabase client.